//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GallerySite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UsersASP
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Поле должно быть заполнено")]
        [DisplayName("Имя пользователя")]
        public string name { get; set; }
        [Required(ErrorMessage = "Поле должно быть заполнено")]
        [DisplayName("Пароль")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [DisplayName("Роль")]
        public string role { get; set; }
    }
}
