//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GallerySite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Договор_с_автором
    {
        public int Номер { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Пожалуйста, введите код автора.")]
        [StringLength(4, ErrorMessage = "Код не может быть длиннее 4 символов.")]
        public Nullable<int> Автор { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Пожалуйста, введите код экспоната.")]
        [StringLength(4, ErrorMessage = "Код не может быть длиннее 4 символов.")]
        public Nullable<int> Экспонат { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Пожалуйста, введите цену оплаты.")]
        [Range(0, 50000)]
        //[StringLength(6, ErrorMessage = "Цена не может быть длиннее 5 символов.")]
        public Nullable<decimal> Цена_оплаты_услуг { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Экспонат Экспонат1 { get; set; }
    }
}
