//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GallerySite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Договор_на_продажу
    {
        public int Код_договора { get; set; }
        public Nullable<int> Экспонат { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Пожалуйста, введите цену экспоната.")]
        [StringLength(10, ErrorMessage = "Цена не может быть длиннее 10 символов.")]
        public Nullable<decimal> Цена_экспоната { get; set; }
        public Nullable<int> Покупатель { get; set; }
        //[Required(AllowEmptyStrings = false, ErrorMessage = "Пожалуйста, введите сумму налога.")]
        //[StringLength(10, ErrorMessage = "Цена не может быть длиннее 10 символов.")]
        public Nullable<decimal> Налог { get; set; }
        public Nullable<int> Комиссия { get; set; }
        public Nullable<decimal> Доход_галереи { get; set; }
        public Nullable<decimal> Гонорар { get; set; }
    
        public virtual Экспонат Экспонат1 { get; set; }
        public virtual Клиент Клиент { get; set; }
    }
}
