//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GallerySite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Экспонат
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Экспонат()
        {
            this.Договор_на_продажу = new HashSet<Договор_на_продажу>();
            this.Договор_с_автором = new HashSet<Договор_с_автором>();
        }
    
        public int Код_экспоната { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Пожалуйста, введите наименование.")]
        [StringLength(20, ErrorMessage = "Наименование не может быть длиннее 20 символов.")]
        public string Наименование { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Пожалуйста, обозначьте вид искусства.")]
        [StringLength(10, ErrorMessage = "Вид искусства не может быть длиннее 10 символов.")]
        public string Вид_искусства { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Пожалуйста, введите путь изображения.")]
        [StringLength(25, ErrorMessage = "Путь не может быть длиннее 25 символов.")]
        public string Изображение { get; set; }
        public Nullable<System.DateTime> Срок_экспонирования { get; set; }
        public string Статус { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Пожалуйста, введите код выставки.")]
        [StringLength(2, ErrorMessage = "Код выставки не может быть длиннее 2 символов.")]
        public Nullable<int> Код_выставки { get; set; }
    
        public virtual Выставка Выставка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договор_на_продажу> Договор_на_продажу { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договор_с_автором> Договор_с_автором { get; set; }
    }
}
